return{
   ["\\bigcap"]="∩",
   ["\\bigcirc"]="○",
   ["\\bigcup"]="∪",
   ["\\bigodot"]="⊙",
   ["\\bigoplus"]="⊕",
   ["\\bigotimes"]="⊗",
   ["\\bigsqcup"]="⊔",
   ["\\bigtriangledown"]="∇",
   ["\\bigtriangleup"]="∆",
   ["\\bigvee"]="⋁",
   ["\\bigwedge"]="⋀",
   ["\\int"]="∫",--bop
   ["\\oint"]="∮",--bop
   ["\\prod"]="∏",--bop
   ["\\sum"]="∑",--bop
}
